import type { Preview } from '@storybook/nextjs-vite'

// The design tokens, compiled to CSS custom properties (e.g. --color-background-page).
// Generated by `npm run tokens` from tokens/tokens.json — see build/css/tokens.css.
import '../build/css/tokens.css'

const preview: Preview = {
  parameters: {
    controls: {
      matchers: {
       color: /(background|color)$/i,
       date: /Date$/i,
      },
    },

    a11y: {
      // 'todo' - show a11y violations in the test UI only
      // 'error' - fail CI on a11y violations
      // 'off' - skip a11y checks entirely
      test: 'todo'
    },

    // This product only ships a dark theme, so Storybook offers one
    // background — the app's real page background token — rather than a
    // light/dark switcher that would suggest a light mode exists.
    backgrounds: {
      options: {
        dark: { name: 'Dark', value: 'var(--color-background-page)' },
      },
    },

    // "Documentation" (docs/autodocs) pages render their stories inline in
    // the page, not inside the viewport-constrained canvas iframe, so they
    // naturally use the full page width — useful for something like a page
    // of color swatches. Set explicitly so this stays true even if a future
    // Storybook version changes its default.
    docs: {
      story: { inline: true },
    },
  },

  initialGlobals: {
    backgrounds: { value: 'dark' },
    // iPhone 13/14-width canvas (390px) as the default for individual
    // component stories, since this product is mobile-iOS-only.
    viewport: { value: 'iphone13' },
  },
};

export default preview;
