import { definePreview } from '@storybook/nextjs-vite'
import { parameters as docsParameters } from '@storybook/addon-docs/preview'
import { sb } from 'storybook/test'

// The design tokens, compiled to CSS custom properties (e.g. --color-background-page).
// Generated by `npm run tokens` from tokens/tokens.json — see build/css/tokens.css.
import '../build/css/tokens.css'

// RecallScreen and SessionEndScreen both call next/navigation's useRouter().
// This installed Storybook version doesn't auto-mock it just from the
// nextjs-vite framework being registered — without an explicit mock, the
// real Next.js implementation runs outside a real app router and throws
// "invariant expected app router to be mounted." Auto-mock (not spy) here;
// each story that navigates supplies real return values via
// mocked(useRouter).mockReturnValue(...) in its own beforeEach.
sb.mock(import('next/navigation'))

export default definePreview({
  addons: [],
  parameters: {
    controls: {
      matchers: {
       color: /(background|color)$/i,
       date: /Date$/i,
      },
    },

    a11y: {
      // 'todo' - show a11y violations in the test UI only
      // 'error' - fail CI on a11y violations
      // 'off' - skip a11y checks entirely
      test: 'todo'
    },

    // This product only ships a dark theme, so Storybook offers one
    // background — the app's real page background token — rather than a
    // light/dark switcher that would suggest a light mode exists.
    backgrounds: {
      options: {
        dark: { name: 'Dark', value: 'var(--color-background-page)' },
      },
    },

    // The product is mobile-iOS-only, so the viewport addon offers a
    // single 390px iPhone 13/14 canvas instead of the desktop/tablet
    // sizes it ships with by default. (The addon's default option set,
    // MINIMAL_VIEWPORTS, doesn't include the built-in "iphone13" preset,
    // so pointing initialGlobals at that key alone silently fell back to
    // its own first default, "Small mobile" at 320px — this replaces the
    // option set so the 390px default actually resolves.)
    viewport: {
      options: {
        mobile: {
          name: 'iPhone 13/14',
          styles: { width: '390px', height: '844px' },
          type: 'mobile',
        },
      },
    },

    // "Documentation" (docs/autodocs) pages render their stories inline in
    // the page, not inside the viewport-constrained canvas iframe, so they
    // naturally use the full page width — useful for something like a page
    // of color swatches. Set explicitly so this stays true even if a future
    // Storybook version changes its default.
    //
    // docsParameters spread first: addon-docs's own docs.renderer is what
    // actually renders a Docs page's content. definePreview doesn't compose
    // it in automatically the way the classic `export default { parameters }`
    // shape used to — without it, every Docs page throws
    // "docsParameter.renderer is not a function" instead of rendering.
    docs: {
      ...docsParameters.docs,
      story: { inline: true },
    },
  },

  initialGlobals: {
    backgrounds: { value: 'dark' },
    // iPhone 13/14-width canvas (390px) as the default for individual
    // component stories, since this product is mobile-iOS-only.
    viewport: { value: 'mobile' },
  },
});
